### ISSUE TITLE
Arrow visibility after being shot

### ISSUE THREAD

**Issue by jonamireh** [jamireh/FruitNinja#12]
They get smaller due to projection/harder to see once they move farther away

**Comment by petegodkin** [comment]
What should we do about this? Like put a trail or something?

**Comment by jonamireh** [comment]
I hope to be able to add a white-trail (Windwake-esque) during the shot of the arrow.

**Comment by jonamireh** [comment]
I haven't implemented it yet but for future reference here's some psuedo code:
- Record the amount of time that has passed since the arrow's been shot in ProjectileMovementComponent.
- After a time t, ask the ArcShader to render the sphere's in the path of the arrow from time (t - TIME_CONST to t) where TIME_CONST is an amount of time required to pass in order to qualify the white trail. Linear attenuation of alpha from near 0 at (t - LENGTH_CONST) to 1 at t.
- After the shot's finished, disable the white trail and re-enable the red shot projection.

Syncing ArcShader state is the trickiest part; there's RED_PROJECTION, WHITE_TRAIL, and NONE.
